const translateKeys = {
  MAIN_PAGE: 'main page',
  MY_COLLECTON: 'my collection',
  LOG_OUT: 'log out',
  LOG_IN: 'log in',
  ADMIN_PANEL: 'admin panel',
  CREATE: 'create',
  EDIT: 'edit',
  DELETE: 'delete',
  AUTOR: 'autor',
  TYPE: 'type',
  BACK: 'back',
  NONE_COLLECTIONS: 'none collections',
  WITHOUT_COLLECTIONS: 'without collections',
  HAVENT_COLLECTIONS: "haven't collections",
  NEW_ITEM: 'new item',
  POST_DESCRIPTION: 'post description',
  SAVE: 'save',
  CLOSE: 'close',
  WRITE_TAG: 'write tag',
  CHOOSE_POST: 'choose post',
  CHOOSE: 'choose',
  POST_NAME: 'post name',
  CREATE_COLLECTION: 'create collection',
  COLLECTION_NAME: 'collection name',
  DESCRIPTION: 'description',
  SELECT_COLLECTION: 'select collection',
  CHOOSE_COLLECTION: 'choose collection',
  COLLECTION_DESCRIPTION: 'collection description',
  ADDITIONAL_FIELDS: 'additional fields',
  UPLOAD: 'upload',
  ADD_FIELD: 'add field',
  UPLOAD_FIELD: 'upload field',
  UPLOAD_ERROR: 'upload error',
  FIELD_REQUIRED: 'field required',
  USERNAME: 'username',
  PASSWORD: 'password',
  EMAIL: 'email',
  EMAIL_ERROR: 'email error',
  HAVE_ACCOUNT: 'have account',
  SING_IN: 'sing in',
  SING_UP: 'sing up',
  SUBMIT: 'submit',
  PASSWORD_ERROR: 'password error',
  UNBLOCK: 'unblock',
  BLOCK: 'block',
  GET_ADMIN: 'get admin',
  PIC_UP_ADMIN: 'pickUpAdmin',
  CHECKBOX: 'checkbox',
  ROLE: 'role',
  ID: 'id',
  TAGS: 'tags',
  CHOOSE_USER: 'choose user',
  REPEATE_PASSWORD: 'repeat password',
  PASSWORDS_DONT_MATCH: "passwords don't match",
  TO_MAIN_PAGE: 'to main page',
  BOOKS: 'books',
  CLOTHES: 'clothes',
  MUSIK: 'music',
  SELECT_FIELD_TO_ADD: 'select field to add',
  ADDED_POST: 'added post',
  LAST_POSTS: 'last posts',
  LAGEST_COLLECTIONS: 'lagest collections',
  TO_ADMIN_PANEL: 'to admin panel',
  CHECK_USERS_COLLECTIONS: 'Check users collections',
  SHOW_ALL_TAGS: 'show all tags',
  TAGS_CLOUD: 'tags cloud',
  FILE_ERROR: 'file error',
  WRITE_A_COMMENT: 'write a comment',
  SEND: 'send',
  FIELD_MAX_LENGTH: 'field max length',
  SUCCESS_REGISTER: 'success register',
  RESEND: 'resend',
  SEND_EMAIL: 'send email',
  CLEAR: 'clear',
  HIDE: 'hide',
  SHOW: 'show',
  SEARCH_THROUGH_COLLECTIONS: 'search through collections',
  RESEND_EMAIL: 'resend email',
  NEW: 'new',
  OLD: 'old',
  DISPLAY: 'display',
  SEARCH_COLLECTIONS: 'search collections',
  EXPORT_CSV: 'csv export',
  NUMBER: 'number',
  TEXT: 'text',
  MULTILINE_TEXT: 'multiline text',
  CHECKBOX_FIELD: 'checkbox field',
  DATE: 'date',
};

export default translateKeys;
